version: '3.8'

services:
    nginx:
        depends_on:
            - reactjs
        restart: always
        build:
            dockerfile: Dockerfile
            context: ./nginx
        ports:
            - '8085:80'
            - '80:80'
            - '443:443'
        volumes:
            - ./logs/nginx:/var/log/nginx/

    reactjs:
        stdin_open: true
        environment:
            - CHOKIDAR_USEPOLLING=true
        build:
            dockerfile: Dockerfile
            context: ./reactjs
        volumes:
            - /app/node_modules
            - ./reactjs:/app
